### ISSUE TITLE
Storage Hooks

### ISSUE THREAD

**Issue by ChrisMacNaughton** [juju/juju#4249]
I'm working on storage hooks for a charm and am running into errors because the hooks run before the install hook. This only seems to happen when I run `juju deploy --storage="2T,2" ...` rather than when I do `juju storage add ...`.

In essence, the storage hook is linked to a hooks.py file that imports charmhelpers/fetch and bails on Xenial with ImportError: No module named apt. The install hook for this charm is NOT linked to this hooks.py, but rather is a bash script that sets up the environment by doing things like installing apt before calling a function in the hooks.py.

The charm exhibiting this behavious is [ceph-osd](https://jujucharms.com/cep-osd/) but I expect it would occur with many charms on their storage-attaching hooks.

**Comment by ChrisMacNaughton** [comment]
it seems like the install hook is not being run in this circumstance. After running `juju resolved ceph/1` I get:

```
2016-01-31 13:03:02 INFO osd-devices-storage-attached Traceback (most recent call last):
2016-01-31 13:03:02 INFO osd-devices-storage-attached   File "/var/lib/juju/agents/unit-ceph-osd-1/charm/hooks/osd-devices-storage-attached", line 16, in <module>
2016-01-31 13:03:02 INFO osd-devices-storage-attached     import ceph
2016-01-31 13:03:02 INFO osd-devices-storage-attached   File "/var/lib/juju/agents/unit-ceph-osd-1/charm/hooks/ceph.py", line 39, in <module>
2016-01-31 13:03:02 INFO osd-devices-storage-attached     from utils import (
2016-01-31 13:03:02 INFO osd-devices-storage-attached   File "/var/lib/juju/agents/unit-ceph-osd-1/charm/hooks/utils.py", line 36, in <module>
2016-01-31 13:03:02 INFO osd-devices-storage-attached     apt_install(filter_installed_packages(['python-jinja2']),
2016-01-31 13:03:02 INFO osd-devices-storage-attached   File "/var/lib/juju/agents/unit-ceph-osd-1/charm/hooks/charmhelpers/fetch/__init__.py", line 162, in filter_installed_packages
2016-01-31 13:03:02 INFO osd-devices-storage-attached     cache = apt_cache()
2016-01-31 13:03:02 INFO osd-devices-storage-attached   File "/var/lib/juju/agents/unit-ceph-osd-1/charm/hooks/charmhelpers/fetch/__init__.py", line 177, in apt_cache
2016-01-31 13:03:02 INFO osd-devices-storage-attached     from apt import apt_pkg
2016-01-31 13:03:02 INFO osd-devices-storage-attached ImportError: No module named apt
2016-01-31 13:03:02 ERROR juju.worker.uniter.operation runhook.go:107 hook "osd-devices-storage-attached" failed: exit status 1
2016-01-31 13:13:07 INFO config-changed Traceback (most recent call last):
2016-01-31 13:13:07 INFO config-changed   File "/var/lib/juju/agents/unit-ceph-osd-1/charm/hooks/config-changed", line 16, in <module>
2016-01-31 13:13:07 INFO config-changed     import ceph
2016-01-31 13:13:07 INFO config-changed   File "/var/lib/juju/agents/unit-ceph-osd-1/charm/hooks/ceph.py", line 39, in <module>
2016-01-31 13:13:07 INFO config-changed     from utils import (
2016-01-31 13:13:07 INFO config-changed   File "/var/lib/juju/agents/unit-ceph-osd-1/charm/hooks/utils.py", line 36, in <module>
2016-01-31 13:13:07 INFO config-changed     apt_install(filter_installed_packages(['python-jinja2']),
2016-01-31 13:13:07 INFO config-changed   File "/var/lib/juju/agents/unit-ceph-osd-1/charm/hooks/charmhelpers/fetch/__init__.py", line 162, in filter_installed_packages
2016-01-31 13:13:07 INFO config-changed     cache = apt_cache()
2016-01-31 13:13:07 INFO config-changed   File "/var/lib/juju/agents/unit-ceph-osd-1/charm/hooks/charmhelpers/fetch/__init__.py", line 177, in apt_cache
2016-01-31 13:13:07 INFO config-changed     from apt import apt_pkg
2016-01-31 13:13:07 INFO config-changed ImportError: No module named apt
2016-01-31 13:13:07 ERROR juju.worker.uniter.operation runhook.go:107 hook "config-changed" failed: exit status 1
```

When searching through `/var/log/juju/unit-ceph-osd-1.log`, there is no entries indicating that the install hook is ever run.

**Comment by ChrisMacNaughton** [comment]
Opened https://bugs.launchpad.net/juju-core/+bug/1540076 to track on LP
