### ISSUE TITLE
[s390x] regression, fails to bootstrap on s390x

### ISSUE THREAD

**Issue by xnox** [juju/juju#4656]
```
$ sudo juju bootstrap --upload-tools --config default-series=xenial take2 lxd
Creating Juju controller "local.take2" on lxd/localhost
Bootstrapping model "take2"
Starting new instance for initial controller
Launching instance
ERROR unexpected problem parsing hardware info: bad "arch" characteristic: "s390x" not recognized
 - juju-2d0c9a99-da2a-4394-8a57-d8cb9da8e2ba-machine-0
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x2aa12c80352]

goroutine 1 [running]:
panic(0x2aa13c904c0, 0xc8200140e0)
	/usr/lib/go/src/runtime/panic.go:464 +0x474
github.com/juju/juju/provider/common.Bootstrap(0x3ff90142240, 0xc8201fed60, 0x3ff900fdfd0, 0xc82017eb40, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/ubuntu/go/src/github.com/juju/juju/provider/common/bootstrap.go:50 +0x122
github.com/juju/juju/provider/common.DefaultProvider.BootstrapEnv(0x3ff900fdfd0, 0xc82017eb40, 0x3ff90142240, 0xc8201fed60, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/ubuntu/go/src/github.com/juju/juju/provider/common/provider.go:23 +0x5e
github.com/juju/juju/provider/common.(*DefaultProvider).BootstrapEnv(0xc820367f30, 0x3ff90142240, 0xc8201fed60, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	<autogenerated>:64 +0xf0
github.com/juju/juju/provider/lxd.(*environ).Bootstrap(0xc82017eb40, 0x3ff90142240, 0xc8201fed60, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/ubuntu/go/src/github.com/juju/juju/provider/lxd/environ.go:152 +0x82
github.com/juju/juju/environs/bootstrap.Bootstrap(0x3ff90142240, 0xc8201fed60, 0x3ff900fdfd0, 0xc82017eb40, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/ubuntu/go/src/github.com/juju/juju/environs/bootstrap/bootstrap.go:187 +0x14e4
github.com/juju/juju/cmd/juju/commands.bootstrapFuncs.Bootstrap(0x3ff90142240, 0xc8201fed60, 0x3ff900fdfd0, 0xc82017eb40, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/ubuntu/go/src/github.com/juju/juju/cmd/juju/commands/bootstrap.go:231 +0x68
github.com/juju/juju/cmd/juju/commands.(*bootstrapFuncs).Bootstrap(0x2aa1546e2f0, 0x3ff90142240, 0xc8201fed60, 0x3ff900fdfd0, 0xc82017eb40, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	<autogenerated>:65 +0x10e
github.com/juju/juju/cmd/juju/commands.(*bootstrapCommand).Run(0xc82041c1e0, 0xc8203fa780, 0x0, 0x0)
	/home/ubuntu/go/src/github.com/juju/juju/cmd/juju/commands/bootstrap.go:453 +0x260e
github.com/juju/juju/cmd/modelcmd.(*modelCommandWrapper).Run(0xc82028c120, 0xc8203fa780, 0x0, 0x0)
	<autogenerated>:111 +0x94
github.com/juju/juju/cmd/modelcmd.(*baseCommandWrapper).Run(0xc82028bf00, 0xc8203fa780, 0x0, 0x0)
	/home/ubuntu/go/src/github.com/juju/juju/cmd/modelcmd/base.go:166 +0xe4
github.com/juju/cmd.(*SuperCommand).Run(0xc820164000, 0xc8203fa780, 0x0, 0x0)
	/home/ubuntu/go/src/github.com/juju/cmd/supercommand.go:446 +0x674
github.com/juju/cmd.Main(0x3ff9013f1a0, 0xc820164000, 0xc8203fa780, 0xc82000a0f0, 0x6, 0x6, 0x2aa14375640)
	/home/ubuntu/go/src/github.com/juju/cmd/cmd.go:279 +0x32e
github.com/juju/juju/cmd/juju/commands.Main(0xc82000a0e0, 0x7, 0x7)
	/home/ubuntu/go/src/github.com/juju/juju/cmd/juju/commands/main.go:83 +0x5aa
main.main()
	/home/ubuntu/go/src/github.com/juju/juju/cmd/juju/main.go:27 +0x42
```

**Comment by cherylj** [comment]
Juju bugs are tracked in launchpad.  Opened bug for this issue:  https://bugs.launchpad.net/juju-core/+bug/1554675
