### ISSUE TITLE
juju bootstrap MAAS 2.0 runtime error 

### ISSUE THREAD

**Issue by garyx** [juju/juju#5259]
Hi there, 

I am trying a fresh install of Xenial MAAS. Packages are as follows. 
MAAS 2.0.0~beta3+bzr4941-0ubuntu1
JUJU is beta5 from the devel repository.
I set the correct flag so JUJU can talk to the new 2.0 api in MAAS 2.0

Doing a bootstrap to MAAS fails with a runtime error and here is the debug output as well. 

**$ juju bootstrap cloud maas/xxx.xxx.xxx.xxx  --debug**
2016-04-22 14:30:37 INFO juju.cmd supercommand.go:60 running juju [2.0-beta5 gc go1.6.1]
2016-04-22 14:30:37 INFO cmd cmd.go:141 cloud "maas" not found, trying as a provider name
2016-04-22 14:30:37 DEBUG juju.cmd.juju.commands bootstrap.go:359 preparing controller with config: map[name:admin uuid:b337440a-205f-4739-881f-xxxxxxxxxxxx controller-uuid:b337440a-205f-4739-xxxxxxxxxxxx type:maas]
2016-04-22 14:30:38 DEBUG juju.provider.maas environprovider.go:31 opening model "admin".
2016-04-22 14:30:38 INFO cmd cmd.go:129 Creating Juju controller "local.viv-ext-cloud" on maas/10.20.40.2
2016-04-22 14:30:38 INFO juju.cmd.juju.commands bootstrap.go:482 combined bootstrap constraints: 
2016-04-22 14:30:38 INFO juju.network network.go:351 setting prefer-ipv6 to false
2016-04-22 14:30:38 INFO cmd cmd.go:129 Bootstrapping model "admin"
2016-04-22 14:30:38 DEBUG juju.environs.bootstrap bootstrap.go:153 model "admin" supports service/machine networks: true
2016-04-22 14:30:38 DEBUG juju.environs.bootstrap bootstrap.go:155 network management by juju enabled: true
2016-04-22 14:30:38 INFO juju.environs.bootstrap tools.go:90 looking for bootstrap tools: version=2.0-beta5
2016-04-22 14:30:38 INFO juju.environs.tools tools.go:106 finding tools in stream "devel"
2016-04-22 14:30:38 INFO juju.environs.tools tools.go:108 reading tools with major.minor version 2.0
2016-04-22 14:30:38 INFO juju.environs.tools tools.go:116 filtering tools by version: 2.0-beta5
2016-04-22 14:30:38 DEBUG juju.environs.tools urls.go:109 trying datasource "keystone catalog"
2016-04-22 14:30:38 DEBUG juju.environs.simplestreams simplestreams.go:674 using default candidate for content id "com.ubuntu.juju:devel:tools" are {20160220 mirrors:1.0 content-download streams/v1/cpc-mirrors.sjson []}
2016-04-22 14:30:40 INFO cmd cmd.go:129 Starting new instance for initial controller
Launching instance
2016-04-22 14:30:41 WARNING juju.provider.maas environ.go:731 no architecture was specified, acquiring an arbitrary node
2016-04-22 14:30:41 DEBUG juju.cloudconfig.instancecfg instancecfg.go:626 Setting numa ctl preference to false
2016-04-22 14:30:41 DEBUG juju.service discovery.go:59 discovered init system "systemd" from series "xenial"
2016-04-22 14:30:41 DEBUG juju.provider.maas environ.go:986 maas user data; 6396 bytes
2016-04-22 14:30:41 DEBUG juju.provider.maas interfaces.go:274 interface "eno4" has no address
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x1196930]

goroutine 1 [running]:
panic(0x1f88f60, 0xc8200100d0)
	/usr/lib/go-1.6/src/runtime/panic.go:464 +0x3e6
github.com/juju/gomaasapi.(*subnet).CIDR(0x0, 0x7f9808659858, 0x0)
	/build/juju-core-zVx9R9/juju-core-2.0-beta5/src/github.com/juju/gomaasapi/subnet.go:56 +0x20
github.com/juju/juju/provider/maas.maas2NetworkInterfaces(0xc8201f9f40, 0xc8205e6000, 0x0, 0x0, 0x0, 0x0, 0x0)
	/build/juju-core-zVx9R9/juju-core-2.0-beta5/src/github.com/juju/juju/provider/maas/interfaces.go:289 +0xc64
github.com/juju/juju/provider/maas.(*maasEnviron).StartInstance(0xc8204e41e0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/build/juju-core-zVx9R9/juju-core-2.0-beta5/src/github.com/juju/juju/provider/maas/environ.go:1014 +0x2003
github.com/juju/juju/provider/common.BootstrapInstance(0x7f98129d6028, 0xc82055c9b0, 0x7f981294d350, 0xc8204e41e0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/build/juju-core-zVx9R9/juju-core-2.0-beta5/src/github.com/juju/juju/provider/common/bootstrap.go:145 +0xab1
github.com/juju/juju/provider/maas.(*maasEnviron).Bootstrap(0xc8204e41e0, 0x7f98129d6028, 0xc82055c9b0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/build/juju-core-zVx9R9/juju-core-2.0-beta5/src/github.com/juju/juju/provider/maas/environ.go:174 +0x111
github.com/juju/juju/environs/bootstrap.Bootstrap(0x7f98129d6028, 0xc82055c9b0, 0x7f981294d350, 0xc8204e41e0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/build/juju-core-zVx9R9/juju-core-2.0-beta5/src/github.com/juju/juju/environs/bootstrap/bootstrap.go:205 +0x15f8
github.com/juju/juju/cmd/juju/commands.bootstrapFuncs.Bootstrap(0x7f98129d6028, 0xc82055c9b0, 0x7f981294d350, 0xc8204e41e0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/build/juju-core-zVx9R9/juju-core-2.0-beta5/src/github.com/juju/juju/cmd/juju/commands/bootstrap.go:235 +0x80
github.com/juju/juju/cmd/juju/commands.(*bootstrapFuncs).Bootstrap(0x37145c8, 0x7f98129d6028, 0xc82055c9b0, 0x7f981294d350, 0xc8204e41e0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	<autogenerated>:74 +0xfb
github.com/juju/juju/cmd/juju/commands.(*bootstrapCommand).Run(0xc820238400, 0xc820225360, 0x0, 0x0)
	/build/juju-core-zVx9R9/juju-core-2.0-beta5/src/github.com/juju/juju/cmd/juju/commands/bootstrap.go:523 +0x2e8a
github.com/juju/juju/cmd/modelcmd.(*modelCommandWrapper).Run(0xc82042c4e0, 0xc820225360, 0x0, 0x0)
	/build/juju-core-zVx9R9/juju-core-2.0-beta5/src/github.com/juju/juju/cmd/modelcmd/modelcommand.go:273 +0x4f
github.com/juju/juju/cmd/modelcmd.(*baseCommandWrapper).Run(0xc8201cc300, 0xc820225360, 0x0, 0x0)
	/build/juju-core-zVx9R9/juju-core-2.0-beta5/src/github.com/juju/juju/cmd/modelcmd/base.go:205 +0xd4
github.com/juju/cmd.(*SuperCommand).Run(0xc8200c2300, 0xc820225360, 0x0, 0x0)
	/build/juju-core-zVx9R9/juju-core-2.0-beta5/src/github.com/juju/cmd/supercommand.go:446 +0x688
github.com/juju/cmd.Main(0x7f98129d4108, 0xc8200c2300, 0xc820225360, 0xc82000a060, 0x4, 0x4, 0x2609370)
	/build/juju-core-zVx9R9/juju-core-2.0-beta5/src/github.com/juju/cmd/cmd.go:280 +0x2f0
github.com/juju/juju/cmd/juju/commands.Main(0xc82000a050, 0x5, 0x5)
	/build/juju-core-zVx9R9/juju-core-2.0-beta5/src/github.com/juju/juju/cmd/juju/commands/main.go:131 +0x51d
main.main()
	/build/juju-core-zVx9R9/juju-core-2.0-beta5/src/github.com/juju/juju/cmd/juju/main.go:27 +0x3b

**Comment by cherylj** [comment]
Thanks for the report.  We track bugs for Juju in launchpad, so I've opened this bug report for you:

https://bugs.launchpad.net/juju-core/+bug/1573659

**Comment by garyx** [comment]
Ahh ofc, my bad. Just ran to github for some reason.
