### ISSUE TITLE
Panic when destroying controller

### ISSUE THREAD

**Issue by anthonydillon** [juju/juju#6039]
I have a single controller listed `uitest` set up on aws. When I try and destroy the controller I get the following error:
```
juju destroy-controller uitest
WARNING! This command will destroy the "uitest" controller.
This includes all machines, applications, data and other resources.

Continue? (y/N):y
panic: interface conversion: interface is nil, not bool

goroutine 1 [running]:
panic(0x2083480, 0xc820414b40)
        /usr/lib/go-1.6/src/runtime/panic.go:481 +0x3e6
github.com/juju/juju/provider/ec2.validateConfig(0xc82046bbb0, 0x0, 0x23, 0x0, 0x0)
        /build/juju-core-eScfM0/juju-core-2.0-beta15/src/github.com/juju/juju/provider/ec2/config.go:104 +0xc30
github.com/juju/juju/provider/ec2.environProvider.Validate(0xc82046bbb0, 0x0, 0x9, 0x0, 0x0)
        /build/juju-core-eScfM0/juju-core-2.0-beta15/src/github.com/juju/juju/provider/ec2/provider.go:110 +0x46
github.com/juju/juju/provider/ec2.environProvider.newConfig(0xc82046bbb0, 0x2852820, 0x0, 0x0)
        /build/juju-core-eScfM0/juju-core-2.0-beta15/src/github.com/juju/juju/provider/ec2/config.go:58 +0x3a
github.com/juju/juju/provider/ec2.(*environ).SetConfig(0xc8202e4c30, 0xc82046bbb0, 0x0, 0x0)
        /build/juju-core-eScfM0/juju-core-2.0-beta15/src/github.com/juju/juju/provider/ec2/environ.go:84 +0x31
github.com/juju/juju/provider/ec2.environProvider.Open(0xc82046a8e8, 0x3, 0xc82046a920, 0x3, 0xc82046a940, 0x9, 0xc82029ad50, 0x26, 0x0, 0x0, ...)
        /build/juju-core-eScfM0/juju-core-2.0-beta15/src/github.com/juju/juju/provider/ec2/provider.go:51 +0x30d
github.com/juju/juju/provider/ec2.(*environProvider).Open(0x38b33c8, 0xc82046a8e8, 0x3, 0xc82046a920, 0x3, 0xc82046a940, 0x9, 0xc82029ad50, 0x26, 0x0, ...)
        <autogenerated>:102 +0xce
github.com/juju/juju/environs.New(0xc82046a8e8, 0x3, 0xc82046a920, 0x3, 0xc82046a940, 0x9, 0xc82029ad50, 0x26, 0x0, 0x0, ...)
        /build/juju-core-eScfM0/juju-core-2.0-beta15/src/github.com/juju/juju/environs/open.go:21 +0xf8
github.com/juju/juju/cmd/juju/controller.(*destroyCommandBase).getControllerEnvironFromStore(0xc8203f1540, 0x7fbd005518c0, 0xc8202699b0, 0x7ffff65732a3, 0x6, 0x0, 0x0, 0x0, 0x0)
        /build/juju-core-eScfM0/juju-core-2.0-beta15/src/github.com/juju/juju/cmd/juju/controller/destroy.go:376 +0x285
github.com/juju/juju/cmd/juju/controller.(*destroyCommandBase).getControllerEnviron(0xc8203f1540, 0x7fbd005518c0, 0xc8202699b0, 0x7ffff65732a3, 0x6, 0x7fbd00487430, 0xc8202dd770, 0x0, 0x0, 0x0, ...)
        /build/juju-core-eScfM0/juju-core-2.0-beta15/src/github.com/juju/juju/cmd/juju/controller/destroy.go:348 +0x7a
github.com/juju/juju/cmd/juju/controller.(*destroyCommand).Run(0xc8203f1540, 0xc8202b5ef0, 0x0, 0x0)
        /build/juju-core-eScfM0/juju-core-2.0-beta15/src/github.com/juju/juju/cmd/juju/controller/destroy.go:133 +0x354
github.com/juju/juju/cmd/modelcmd.(*sysCommandWrapper).Run(0xc820420cf0, 0xc8202b5ef0, 0x0, 0x0)
        <autogenerated>:146 +0x65
github.com/juju/juju/cmd/modelcmd.(*baseCommandWrapper).Run(0xc820416c80, 0xc8202b5ef0, 0x0, 0x0)
        /build/juju-core-eScfM0/juju-core-2.0-beta15/src/github.com/juju/juju/cmd/modelcmd/base.go:268 +0xd4
github.com/juju/cmd.(*SuperCommand).Run(0xc8203dc480, 0xc8202b5ef0, 0x0, 0x0)
        /build/juju-core-eScfM0/juju-core-2.0-beta15/src/github.com/juju/cmd/supercommand.go:456 +0x688
github.com/juju/cmd.Main(0x7fbd00514380, 0xc8203dc480, 0xc8202b5ef0, 0xc82000a490, 0x2, 0x2, 0x4b22fa)
        /build/juju-core-eScfM0/juju-core-2.0-beta15/src/github.com/juju/cmd/cmd.go:280 +0x2f0
github.com/juju/juju/cmd/juju/commands.main.Run(0x2b8d1b8, 0xc82000a480, 0x3, 0x3, 0x2519b40)
        /build/juju-core-eScfM0/juju-core-2.0-beta15/src/github.com/juju/juju/cmd/juju/commands/main.go:149 +0x5bb
github.com/juju/juju/cmd/juju/commands.Main(0xc82000a480, 0x3, 0x3, 0xc820000180)
        /build/juju-core-eScfM0/juju-core-2.0-beta15/src/github.com/juju/juju/cmd/juju/commands/main.go:114 +0x48
main.main()
        /build/juju-core-eScfM0/juju-core-2.0-beta15/src/github.com/juju/juju/cmd/juju/main.go:27 +0x3b
```

Running kill controlller results in the same error:

```
juju kill-controller uitest -y
panic: interface conversion: interface is nil, not bool

goroutine 1 [running]:
panic(0x2083480, 0xc8203f7200)
        /usr/lib/go-1.6/src/runtime/panic.go:481 +0x3e6
github.com/juju/juju/provider/ec2.validateConfig(0xc820232cd0, 0x0, 0x23, 0x0, 0x0)
        /build/juju-core-eScfM0/juju-core-2.0-beta15/src/github.com/juju/juju/provider/ec2/config.go:104 +0xc30
github.com/juju/juju/provider/ec2.environProvider.Validate(0xc820232cd0, 0x0, 0x9, 0x0, 0x0)
        /build/juju-core-eScfM0/juju-core-2.0-beta15/src/github.com/juju/juju/provider/ec2/provider.go:110 +0x46
github.com/juju/juju/provider/ec2.environProvider.newConfig(0xc820232cd0, 0x2852820, 0x0, 0x0)
        /build/juju-core-eScfM0/juju-core-2.0-beta15/src/github.com/juju/juju/provider/ec2/config.go:58 +0x3a
github.com/juju/juju/provider/ec2.(*environ).SetConfig(0xc820249380, 0xc820232cd0, 0x0, 0x0)
        /build/juju-core-eScfM0/juju-core-2.0-beta15/src/github.com/juju/juju/provider/ec2/environ.go:84 +0x31
github.com/juju/juju/provider/ec2.environProvider.Open(0xc820431b28, 0x3, 0xc820431be0, 0x3, 0xc820431c00, 0x9, 0xc820231e90, 0x26, 0x0, 0x0, ...)
        /build/juju-core-eScfM0/juju-core-2.0-beta15/src/github.com/juju/juju/provider/ec2/provider.go:51 +0x30d
github.com/juju/juju/provider/ec2.(*environProvider).Open(0x38b33c8, 0xc820431b28, 0x3, 0xc820431be0, 0x3, 0xc820431c00, 0x9, 0xc820231e90, 0x26, 0x0, ...)
        <autogenerated>:102 +0xce
github.com/juju/juju/environs.New(0xc820431b28, 0x3, 0xc820431be0, 0x3, 0xc820431c00, 0x9, 0xc820231e90, 0x26, 0x0, 0x0, ...)
        /build/juju-core-eScfM0/juju-core-2.0-beta15/src/github.com/juju/juju/environs/open.go:21 +0xf8
github.com/juju/juju/cmd/juju/controller.(*destroyCommandBase).getControllerEnvironFromStore(0xc8203e39e0, 0x7f9ffe013b40, 0xc82045c0f0, 0x7fff96f8a2a0, 0x6, 0x0, 0x0, 0x0, 0x0)
        /build/juju-core-eScfM0/juju-core-2.0-beta15/src/github.com/juju/juju/cmd/juju/controller/destroy.go:376 +0x285
github.com/juju/juju/cmd/juju/controller.(*destroyCommandBase).getControllerEnviron(0xc8203e39e0, 0x7f9ffe013b40, 0xc82045c0f0, 0x7fff96f8a2a0, 0x6, 0x7f9ffdfc5cf0, 0xc820230270, 0x0, 0x0, 0x0, ...)
        /build/juju-core-eScfM0/juju-core-2.0-beta15/src/github.com/juju/juju/cmd/juju/controller/destroy.go:348 +0x7a
github.com/juju/juju/cmd/juju/controller.(*killCommand).Run(0xc8203e39e0, 0xc82022fd60, 0x0, 0x0)
        /build/juju-core-eScfM0/juju-core-2.0-beta15/src/github.com/juju/juju/cmd/juju/controller/kill.go:114 +0x2b9
github.com/juju/juju/cmd/modelcmd.(*sysCommandWrapper).Run(0xc8204015f0, 0xc82022fd60, 0x0, 0x0)
        <autogenerated>:146 +0x65
github.com/juju/juju/cmd/modelcmd.(*baseCommandWrapper).Run(0xc82030b570, 0xc82022fd60, 0x0, 0x0)
        /build/juju-core-eScfM0/juju-core-2.0-beta15/src/github.com/juju/juju/cmd/modelcmd/base.go:268 +0xd4
github.com/juju/cmd.(*SuperCommand).Run(0xc8203be480, 0xc82022fd60, 0x0, 0x0)
        /build/juju-core-eScfM0/juju-core-2.0-beta15/src/github.com/juju/cmd/supercommand.go:456 +0x688
github.com/juju/cmd.Main(0x7f9ffe011968, 0xc8203be480, 0xc82022fd60, 0xc82000a3d0, 0x3, 0x3, 0x4b22fa)
        /build/juju-core-eScfM0/juju-core-2.0-beta15/src/github.com/juju/cmd/cmd.go:280 +0x2f0
github.com/juju/juju/cmd/juju/commands.main.Run(0x2b8d1b8, 0xc82000a3c0, 0x4, 0x4, 0x2519b40)
        /build/juju-core-eScfM0/juju-core-2.0-beta15/src/github.com/juju/juju/cmd/juju/commands/main.go:149 +0x5bb
github.com/juju/juju/cmd/juju/commands.Main(0xc82000a3c0, 0x4, 0x4, 0xc820000180)
        /build/juju-core-eScfM0/juju-core-2.0-beta15/src/github.com/juju/juju/cmd/juju/commands/main.go:114 +0x48
main.main()
        /build/juju-core-eScfM0/juju-core-2.0-beta15/src/github.com/juju/juju/cmd/juju/main.go:27 +0x3b
```

I checked aws console and I have no instances running.

**Comment by anastasiamac** [comment]
Anthony,
We track our bugs in launchpad - https://bugs.launchpad.net/juju-core/
Please file this issue as a bug there.

**Comment by anthonydillon** [comment]
Done thanks https://bugs.launchpad.net/juju-core/+bug/1614929.
